pipeline:
  name: mypipeline
  identifier: mypipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage0
        identifier: stage0
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: step000
                  identifier: step000
                  type: HarnessApproval
                  timeout: 10m
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: false
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
